# Generated by Django 3.2.6 on 2021-08-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="shop/no-product-image.jpeg", upload_to="blog"
            ),
        ),
    ]
