name: Github Backend Build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7.9]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install main packages
        run: |
          pip install --upgrade pip poetry virtualenv
      - name: Create virtual environment
        run: |
          virtualenv .venv -p python3
      - name: Install dependencies
        run: |
          source .venv/bin/activate
          poetry install
      - name: Lint with flake8
        run: |
          source .venv/bin/activate
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
